<?php

function groceries_menu() {
    $items = array();
    $items['groceries'] = array(
        'title' => "Groceries List",
        'page callback' => 'groceries_display',
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
        );
    return $items;
}
function groceries_display() {
    $grocery_list = array();
    $grocery_list['eggs'] = array(
        'price' => 1.99,
        'quantity' => 2,
        );
    $grocery_list['bacon'] = array(
        'price' => 1.99,
        'quantity' => 5,
        );
    $grocery_list['potatoes'] = array(
        'price' => .99,
        'quantity' => 6,
        );
    $list = "";

    foreach($grocery_list as $key => $element) {
        $list .= '<h1>' . $key . '</h1>';
        foreach ($element as $key => $value) {
            $list .= '<li>' . $key . ' ' . $value . '</li>';
        }
        $total = $element['price'] * $element['quantity'];
        $list .= 'total:   $' . $total;
    }
    return $list;

}